### ISSUE TITLE
Please add license.

### ISSUE THREAD

**Issue by schmidtw** [jensneuse/abstractlogger#1]
Hello, would you please add a license to this code?  It's being used in a different project you contribute to here:
https://github.com/wundergraph/graphql-go-tools

**Comment by jonathanbaker7** [comment]
This is unusable because the author hasn't attached a license.  

Therefore, we can't use Wondergraph Cosmo, because this is a direct dependency.  Because using it would break the law.

I know this may sound like a trivial issue, but the license is pretty important.  Without a license the default is "all rights reserved".  Which means no one else can legally use it.  Don't take my word on it, it's in the GitHub docs:

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by jensneuse** [comment]
> This is unusable because the author hasn't attached a license.
> 
> Therefore, we can't use Wondergraph Cosmo, because this is a direct dependency. Because using it would break the law.
> 
> I know this may sound like a trivial issue, but the license is pretty important. Without a license the default is "all rights reserved". Which means no one else can legally use it. Don't take my word on it, it's in the GitHub docs:
> 
> > However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
> 
> [docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

MIT license added

**Comment by jonathanbaker7** [comment]
Thanks!

Can you do byte-template too?  Thanks so much!

**Comment by jensneuse** [comment]
> Thanks!
> 
> Can you do byte-template too? Thanks so much!

done
